### ISSUE TITLE
Make https and admin tasks idempotent

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#112]
For now these tasks use `tljh-config add-item` to add items to the config.

Even though the same items are added several times since it's a list:

```yaml
users:
  admin:
  - foo
  - foo
```

It means that a call to `tljh-config remove-item` will only remove one item at a time.

cf #111.

**Comment by pierrepo** [comment]
@jtpio I like this way to add admin users on TLJH.

Could we imagine a ansible playbook with a `host`-like file with the list of admin users:
```
users:
  admin:
  - foo
  - foo
```

**Comment by pierrepo** [comment]
Maybe something like this:
```
ansible-playbook admins.yml -i hosts -u ubuntu -correct-option admins
```

Where the `admins` file contains:
```
users:
  admin:
  - foo
  - foo
```

**Comment by jtpio** [comment]
> I like this way to add admin users on TLJH.

Yes I also think it's quite practical :+1: 

Forgot to mention that the above snippet comes from the TLJH config in `/opt/tljh/config/config.yaml`:

```yaml
services:
  cull:
    timeout: 3600
https:
  enabled: true
  letsencrypt:
    email: contact@plasmabio.org
    domains:
    - test.plasmabio.org
users:
  admin:
  - foo
  - foo
```

The main issue is that we are using `tljh-config add-item` which keeps adding entries to the list.

As mentioned in #111 we could try to reset the list with `tljh-config unset users.admin` before adding them all (http://tljh.jupyter.org/en/latest/topic/tljh-config.html#set-unset-a-configuration-property)
