### ISSUE TITLE
Remove the user creation from the site.yml playbook

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#120]
For now the `users.yml` has been included in `site.yml` to ease the creation of test users:

https://github.com/plasmabio/plasmabio/blob/c83a4ba5731709eb3f7919aa36083c8917f98e7e/ansible/site.yml#L4

However these test users should not be created when doing a real deployment.

Instead the documentation could explain how to create users on the server using an Ansible playbook.

**Comment by pierrepo** [comment]
Agreed.
It would be nice to have a kind of config file in which we could list some parameters to the server such as user login and password.
The playbook `users.yml` will then read the file:
```
$ ansible-playbook -i host -u ubuntu users.yml -e @users-config.yml
```
Example for `users-config.yml` (probably not YAML compliant):
```
- users:
    user:
        name: foo
        password: XXXX
    user:
        name: bar
        password: XXXX
```
